---
- name: Postgres Setup
  hosts: all
  gather_facts: true
  become: true
  vars:
    postgres_password: ""
    k3s_username: ""
    k3s_password: ""
    k3s_database: ""
  tasks:
    - name: Install Postgres
      apt:
        name:
          - postgresql-16
          - postgresql-contrib-16
        state: present

    - name: postgresql.conf - listen addresses
      lineinfile:
        path: /etc/postgresql/16/main/postgresql.conf
        search_string: "#listen_addresses = 'localhost'"
        line: "listen_addresses = '*'"
        owner: postgres
        group: postgres
        mode: '0644'

    - name: Change Postgres User Password
      shell:
        executable: "/usr/bin/bash"
        cmd: |
          sudo -u postgres psql template1 -c "ALTER USER postgres with encrypted password '{{ postgres_password }}'"

    - name: pg_hba.conf - line check
      lineinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        state: absent
        regexp: "^# Custom allow all connections from local network"
      check_mode: true
      changed_when: false
      register: pg_hba_check

    - name: pg_hba.conf - local network auth
      when: pg_hba_check.found == 0
      lineinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        line: |-
          # Custom allow all connections from local network
          hostssl all all 192.168.1.0/24 scram-sha-256
          hostssl all all 192.168.20.0/24 scram-sha-256
        owner: postgres
        group: postgres
        mode: '0644'

    - name: Create K3S Database and User
      shell:
        executable: "/usr/bin/bash"
        cmd: |
          sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname = '{{ k3s_database }}';" | grep -q 1 || sudo -u postgres psql -c "CREATE DATABASE {{ k3s_database }};"
          sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname = '{{ k3s_username }}';" | grep -q 1 || sudo -u postgres psql -c "CREATE USER {{ k3s_username }} WITH PASSWORD '{{ k3s_password }}';"
          sudo -u postgres psql -tc "SELECT 1 FROM information_schema.role_table_grants WHERE grantee = '{{ k3s_username }}' AND table_catalog = '{{ k3s_database }}';" | grep -q 1 || sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE {{ k3s_database }} TO {{ k3s_username }};"
          sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname = '{{ k3s_database }}' and datdba = (SELECT usesysid FROM pg_user WHERE usename = '{{ k3s_username }}');" | grep -q 1 || sudo -u postgres psql -c "ALTER DATABASE {{ k3s_database }} OWNER TO {{ k3s_username }};"

    - name: Start Postgres Service
      systemd:
        name: postgresql
        state: restarted
